name: cicd_application_web_api

services:
  mysql:
    build: ./infra/
    container_name: mysql
    volumes:
      # creation d'un volume de persistance
      - ./infra/data:/var/lib/mysql
      # creation d'un volume pour la creation de la BDD
      - ./infra/dump:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - 3396:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot

  api:
    image: louvea/api:latest
    container_name: api
    depends_on:
      - mysql
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/springboot?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    ports:
      - "9010:9000"

  phpMyAdmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    ports:
      - "8090:80"
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  app:
    depends_on:
      - api
    image: louvea/appweb
    container_name: app
    environment:
      - sprintboot.appweb.apiUrl=http://api:9000
    ports:
      - "8080:9001"



volumes:
  data: