name: cicd_application_web_api

services:
  mysql:
    #build: ./infra/
    image: mysql:latest
    container_name: mysql
    volumes:
      # creation d'un volume de persistance
      - ./infra/data:/var/lib/mysql
      # creation d'un volume pour la creation de la BDD
      - ./infra/dump/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 3396:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  api:
    image: louvea/api:latest
    container_name: api
    depends_on:
      - mysql
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/springboot?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    ports:
      - "9010:9000"

  phpMyAdmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    ports:
      - "8090:80"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  app:
    depends_on:
      - api
    image: louvea/appweb
    container_name: app
    environment:
      - sprintboot.appweb.apiUrl=http://api:9000
    ports:
      - "8080:9001"



volumes:
  data: